import {
  assert,
  BoxMap,
  Contract,
  emit,
  Global,
  GlobalState,
  Txn,
  Uint64,
} from '@algorandfoundation/algorand-typescript'
import type { bytes, uint64 } from '@algorandfoundation/algorand-typescript'

/**
 * GreenAfrica Algorand application.
 *
 * This contract is an Algorand-native verification and accounting rail that can
 * run alongside the existing Hedera implementation. The application creator is
 * the writer, matching GreenAfrica's server-managed model where recyclers do
 * not need their own blockchain wallet.
 *
 * IDs are expected to be hashes generated by the backend:
 * - recyclerId: hashed Green ID
 * - rvmId: unique machine identifier
 * - sessionId: unique recycling session identifier
 * - redemptionId: unique redemption identifier
 * - receiptHash: hash of the off-chain receipt/media payload
 */
export class GreenAfricaAlgorand extends Contract {
  public paused = GlobalState<uint64>({ initialValue: Uint64(0) })

  public rvmActive = BoxMap<bytes, uint64>({ keyPrefix: 'rvm:' })
  public recyclerPoints = BoxMap<bytes, uint64>({ keyPrefix: 'points:' })
  public recyclerPet = BoxMap<bytes, uint64>({ keyPrefix: 'pet:' })
  public sessionSeen = BoxMap<bytes, uint64>({ keyPrefix: 'session:' })
  public redemptionSeen = BoxMap<bytes, uint64>({ keyPrefix: 'redeem:' })

  private assertOwner(): void {
    assert(Txn.sender === Global.creatorAddress, 'Not authorized')
  }

  private assertRunning(): void {
    assert(this.paused.value === Uint64(0), 'Paused')
  }

  public setPaused(value: boolean): void {
    this.assertOwner()
    this.paused.value = value ? Uint64(1) : Uint64(0)
    emit('Paused', this.paused.value)
  }

  public registerRvm(rvmId: bytes): void {
    this.assertOwner()

    const rvm = this.rvmActive(rvmId)
    assert(!rvm.exists, 'RVM exists')

    rvm.value = Uint64(1)
    emit('RVMRegistered', rvmId)
  }

  public setRvmActive(rvmId: bytes, active: boolean): void {
    this.assertOwner()

    const rvm = this.rvmActive(rvmId)
    assert(rvm.exists, 'RVM not found')

    rvm.value = active ? Uint64(1) : Uint64(0)
    emit('RVMStatusUpdated', rvmId, rvm.value)
  }

  public registerRecycler(recyclerId: bytes): void {
    this.assertOwner()

    const points = this.recyclerPoints(recyclerId)
    const pet = this.recyclerPet(recyclerId)

    assert(!points.exists, 'Recycler exists')

    points.value = Uint64(0)
    pet.value = Uint64(0)
    emit('RecyclerRegistered', recyclerId)
  }

  public recordDeposit(
    recyclerId: bytes,
    rvmId: bytes,
    petCount: uint64,
    pointsAwarded: uint64,
    sessionId: bytes,
    receiptHash: bytes,
  ): [uint64, uint64] {
    this.assertOwner()
    this.assertRunning()

    assert(petCount > Uint64(0), 'pet=0')
    assert(pointsAwarded > Uint64(0), 'points=0')

    const rvm = this.rvmActive(rvmId)
    const points = this.recyclerPoints(recyclerId)
    const pet = this.recyclerPet(recyclerId)
    const session = this.sessionSeen(sessionId)

    assert(rvm.exists && rvm.value === Uint64(1), 'RVM invalid')
    assert(points.exists && pet.exists, 'Recycler not found')
    assert(!session.exists, 'Session already recorded')

    points.value = points.value + pointsAwarded
    pet.value = pet.value + petCount
    session.value = Uint64(1)

    emit(
      'DepositRecorded',
      recyclerId,
      rvmId,
      petCount,
      pointsAwarded,
      sessionId,
      receiptHash,
    )

    return [points.value, pet.value]
  }

  public redeemPoints(
    recyclerId: bytes,
    pointsToRedeem: uint64,
    redemptionId: bytes,
    destinationHash: bytes,
  ): uint64 {
    this.assertOwner()
    this.assertRunning()

    assert(pointsToRedeem > Uint64(0), 'points=0')

    const points = this.recyclerPoints(recyclerId)
    const redemption = this.redemptionSeen(redemptionId)

    assert(points.exists, 'Recycler not found')
    assert(!redemption.exists, 'Redemption already recorded')
    assert(points.value >= pointsToRedeem, 'Insufficient points')

    points.value = points.value - pointsToRedeem
    redemption.value = Uint64(1)

    emit(
      'PointsRedeemed',
      recyclerId,
      pointsToRedeem,
      redemptionId,
      destinationHash,
      points.value,
    )

    return points.value
  }

  public adjustPoints(recyclerId: bytes, delta: uint64, add: boolean): uint64 {
    this.assertOwner()

    const points = this.recyclerPoints(recyclerId)
    assert(points.exists, 'Recycler not found')

    if (add) {
      points.value = points.value + delta
    } else {
      assert(points.value >= delta, 'Insufficient points')
      points.value = points.value - delta
    }

    emit('PointsAdjusted', recyclerId, delta, add, points.value)
    return points.value
  }

  public getRecycler(recyclerId: bytes): [uint64, uint64] {
    const points = this.recyclerPoints(recyclerId)
    const pet = this.recyclerPet(recyclerId)

    assert(points.exists && pet.exists, 'Recycler not found')
    return [points.value, pet.value]
  }

  public isRvmActive(rvmId: bytes): boolean {
    const rvm = this.rvmActive(rvmId)
    return rvm.exists && rvm.value === Uint64(1)
  }

  public isSessionRecorded(sessionId: bytes): boolean {
    return this.sessionSeen(sessionId).exists
  }
}
